services:
  openapi-mock:
    image: stoplight/prism:5
    command: mock -h 0.0.0.0 --no-multiprocess /spec/openapi.yaml
    ports:
      - "${OPENAPI_MOCK_PORT:-4010}:4010"
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml:ro
